[package]
name = "i_want_gaem"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.22.1"
enum-iterator = "0.7.0"
regex = "1.5.4"
